const WindowFrame = function (content) {
    let frameHead = document.createElement("DIV");
    frameHead.style = "border-bottom: 2px solid #545454; padding-bottom: 40px";
    let titleSide = document.createElement("DIV");
    titleSide.style = "position: absolute; left: 0; right: 40px; height: 40px; background-color: #545454; border-top-left-radius: 0px;";
    let title = document.createElement("H2");
    title.style = "margin: 3px 8px; color: #ffffff;";
    this.title = title;
    titleSide.appendChild(title);
    let btnCloseSide = document.createElement("DIV");
    btnCloseSide.style = "position: absolute; right: 0; width: 40px; height: 40px; background-color: #ff7677; border-left: 2px solid #545454; border-top-right-radius: 0px;";
    let btnClose = document.createElement("A");
    btnClose.innerHTML = '<h3 style="margin: 8px; color: #545454"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></h3>';
    btnCloseSide.appendChild(btnClose);
    this.btnClose = btnClose;
    frameHead.appendChild(titleSide);
    frameHead.appendChild(btnCloseSide);
    this.frameHead = frameHead;
    this.container = content.container;
};